name: clone-test-scenario
description: 'clone test scenario'
inputs:
  repository_url:
    description: 'repository that stores test scenarios'
    required: true
    type: string
  branch_name:
    description: 'branch to checkout'
    required: true
    default: main
    type: string
runs:
  using: "composite"
  steps:
    - name: clone
      run: git clone ${{ inputs.repository_url }}
      shell: pwsh
    - name: checkout
      run: "echo hello"
      shell: pwsh
